version: "3"

services:
  server:
    image: ghcr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    volumes:
      - ./wireguard:/config:ro
    restart: unless-stopped

  ui:
    # build: .
    image: ngoduykhanh/wireguard-ui
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./db:/app/db
      - ./wireguard:/etc/wireguard
    restart: unless-stopped
